[package]
name = "fungible-token"
version = "1.0.0"
authors = ["hack-a-du"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-contract-standards = { workspace = true }
near-sdk = { workspace = true }
