[package]
name = "stakable_nft"
version = "1.0.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-contract-standards = "4.1.1"
near-sdk = "4.1.1"
serde = "1"
serde_json = "1"
borsh = "0.9.3"
