services:
  back:
    image: ghcr.io/hack-a-chain-software/mmc.project/back:latest
    build:
      context: .
      dockerfile: ./packages/back/Dockerfile
    ports:
      - "443:3000"
    environment:
      - PORT=3000
      - RECEIVER_ID=nft.test.near
      - NFT_CONTRACT_ID=nft.test.near
      - ACCOUNT_KEYPAIR=ed25519:3tU5BE8BnNQ9pX89DKepzMAZKQ7NPGCaY63cEtaueTS8iPyarB2rSXBuWLeZQ4LDL9m4oYRZXx936S3oS5MtjyoF
      - NEAR_NETWORK=localnet
      - JWT_SECRET=abacaba
      - JWT_VALID_FOR_S=180
      - AUTH_MESSAGE_VALID_FOR_MS=60000
      - NEAR_NODE_URL=https://rpc.testnet.near.org
    networks:
      - mmc
    depends_on:
      - db
      - contracts

  contracts:
    image: ghcr.io/hack-a-chain-software/mmc.project/contracts:latest
    build:
      context: ./packages/contracts/
    networks:
      - mmc

  db:
    image: postgres:14.5-bullseye
    user: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=abacaba
      - MMC_PASSWORD=abacaba
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./packages/db/src/init.sh:/docker-entrypoint-initdb.d/init.sh
    networks:
      - mmc

volumes:
  pg_data:


networks:
  mmc: {}
