services:
  back:
    image: ghcr.io/hack-a-chain-software/mmc.project/back:latest
    build:
      context: .
      dockerfile: ./packages/back/Dockerfile
    ports:
      - "443:3000"
    environment:
      - PORT=3000
      - RECEIVER_ID=nft.test.near
      - NFT_CONTRACT_ID=nft.test.near
      - ACCOUNT_KEYPAIR=ed25519:3tU5BE8BnNQ9pX89DKepzMAZKQ7NPGCaY63cEtaueTS8iPyarB2rSXBuWLeZQ4LDL9m4oYRZXx936S3oS5MtjyoF
      - NEAR_NETWORK=localnet
      - JWT_SECRET=abacaba
      - JWT_VALID_FOR_S=180
      - AUTH_MESSAGE_VALID_FOR_MS=60000
    networks:
      - mmc
    depends_on:
      - db
      - contracts

  contracts:
    build:
      context: ./packages/contracts/
    networks:
      - mmc

  db:
    image: ghcr.io/hack-a-chain-software/mmc.project/db:latest
    build:
      context: .
      dockerfile: ./packages/db/Dockerfile
    user: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=mmc
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./packages/db/migrations/committed:/docker-entrypoint-initdb.d
    networks:
      - mmc

volumes:
  pg_data:


networks:
  mmc: {}
