[package]
name = "vesting_contract"
version = "1.0.0"
authors = ["vote for pedro"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = "3.1.0"
serde = "1"
serde_json = "1"