cargo-features = ["profile-rustflags"]

[workspace]
members = [
    "./locked_token",
    "./fungible_token",
    "./vesting_contract",
    "./tests"
]

[profile.release]
codegen-units = 1
opt-level = "z" # optimize for binary size without loop vectorization
lto = true # link time optimization
debug = false
panic = "abort"
overflow-checks = true
rustflags = ['-Z unstable-options']

[workspace.dependencies]
# NEAR libraries
near-contract-standards = "4.1.1"
near-sdk = { version = "4.1.1", features = ["abi"] }
near-units = "0.2.0"

schemars = "0.8.11"

# PATCH:
near-abi-client = { path = "near-abi-client-rs/near-abi-client"}
workspaces = { path = "workspaces-rs/workspaces" }
